config/routes.rb
Rails.application.routes.draw do
  get "home/index"
  resources :categories
  resources :products
  resources :brands
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :products
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :brand
  belongs_to :category
  validates :price, numericality: {greater_than_or_equal_to: 0, message: "must be greater than or equal to 0"}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  before_action :set_brand, only: %i[show edit update destroy]

  # GET /brands or /brands.json
  def index
    @brands = Brand.all
  end

  # GET /brands/1 or /brands/1.json
  def show
  end

  # GET /brands/new
  def new
    @brand = Brand.new
  end

  # GET /brands/1/edit
  def edit
  end

  # POST /brands or /brands.json
  def create
    @brand = Brand.new(brand_params)

    respond_to do |format|
      if @brand.save
        format.html { redirect_to @brand, notice: "Brand was successfully created." }
        format.json { render :show, status: :created, location: @brand }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /brands/1 or /brands/1.json
  def update
    respond_to do |format|
      if @brand.update(brand_params)
        format.html { redirect_to @brand, notice: "Brand was successfully updated." }
        format.json { render :show, status: :ok, location: @brand }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brands/1 or /brands/1.json
  def destroy
    @brand.destroy!

    respond_to do |format|
      format.html { redirect_to brands_path, status: :see_other, notice: "Brand was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_brand
    @brand = Brand.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def brand_params
    params.require(:brand).permit(:name, :description)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy!

    respond_to do |format|
      format.html { redirect_to categories_path, status: :see_other, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:name, :description)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[show edit update destroy]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy!

    respond_to do |format|
      format.html { redirect_to products_path, status: :see_other, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def product_params
    params.require(:product).permit(:name, :price, :brand_id, :category_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/brands/_brand.html.erb
<div id="<%= dom_id brand %>">
  <p>
    <strong>Name:</strong>
    <%= brand.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= brand.description %>
  </p>

</div>

app/views/brands/_form.html.erb
<%= form_with(model: brand) do |form| %>
  <% if brand.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(brand.errors.count, "error") %> prohibited this brand from being saved:</h2>

      <ul>
        <% brand.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.textarea :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/brands/edit.html.erb
<% content_for :title, "Editing brand" %>

<h1>Editing brand</h1>

<%= render "form", brand: @brand %>

<br>

<div>
  <%= link_to "Show this brand", @brand %> |
  <%= link_to "Back to brands", brands_path %>
</div>

app/views/brands/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Brands" %>

<h1>Brands</h1>

<div id="brands">
  <% @brands.each do |brand| %>
    <%= render brand %>
    <p>
      <%= link_to "Show this brand", brand %>
    </p>
  <% end %>
</div>

<%= link_to "New brand", new_brand_path %>

app/views/brands/new.html.erb
<% content_for :title, "New brand" %>

<h1>New brand</h1>

<%= render "form", brand: @brand %>

<br>

<div>
  <%= link_to "Back to brands", brands_path %>
</div>

app/views/brands/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @brand %>

<div>
  <%= link_to "Edit this brand", edit_brand_path(@brand) %> |
  <%= link_to "Back to brands", brands_path %>

  <%= button_to "Destroy this brand", @brand, method: :delete %>
</div>

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p>
    <strong>Name:</strong>
    <%= category.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= category.description %>
  </p>

</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.textarea :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<% content_for :title, "Editing category" %>

<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Categories" %>

<h1>Categories</h1>

<div id="categories">
  <% @categories.each do |category| %>
    <%= render category %>
    <p>
      <%= link_to "Show this category", category %>
    </p>
  <% end %>
</div>

<%= link_to "New category", new_category_path %>

app/views/categories/new.html.erb
<% content_for :title, "New category" %>

<h1>New category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @category %>

<div>
  <%= link_to "Edit this category", edit_category_path(@category) %> |
  <%= link_to "Back to categories", categories_path %>

  <%= button_to "Destroy this category", @category, method: :delete %>
</div>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Outfitter Hub" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
  </head>

  <body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <div class="container"> 
    <%= yield %>
  </div>
  
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: @product, class: "needs-validation") do |form| %>
  <% if product.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :category_id, class: "form-label" %>
    <%= form.collection_select :category_id, Category.all, :id, :name, { prompt: "Select a Category" }, class: "form-select" %>
  </div>

  <div class="mb-3">
    <%= form.label :name, class: "form-label" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :price, class: "form-label" %>
    <%= form.text_field :price, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :brand_id, class: "form-label" %>
    <%= form.collection_select :brand_id, Brand.all, :id, :name, { prompt: "Select a Brand" }, class: "form-select" %>
  </div>

  <div class="mb-3">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
  <p>
    <strong>Name:</strong>
    <%= product.name %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= product.price %>
  </p>

  <p>
    <strong>Brand:</strong>
    <%= product.brand_id %>
  </p>

</div>

app/views/products/edit.html.erb
<% content_for :title, "Editing product" %>

<article class="product-edit">
  <header>
    <h1>Edit Product</h1>
  </header>

  <section class="edit-form">
    <%= render "form", product: @product %>
  </section>

  <nav class="product-actions">
    <%= link_to "Show", @product, class: "button" %> |
    <%= link_to "Back to Products", products_path, class: "button" %>
  </nav>
</article>

app/views/products/index.html.erb
<%# rubocop:disable Lint/Syntax %>
<% if notice %>
  <div class="flash-notice"><%= notice %></div>
<% end %>

<% content_for :title, "Products" %>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Brand</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= number_to_currency(product.price) %></td>
        <td><%= product.brand&.name || "N/A" %></td>
        <td><%= product.category&.name || "N/A" %></td>
        <td><%= button_to 'Show', product %></td>
        <td><%= button_to 'Edit', edit_product_path(product) %></td>
        <td><%= button_to 'Delete', product, method: :delete, class: 'button', form: { data: { turbo_confirm: 'Are you sure?' } } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to "New product", new_product_path %>

app/views/products/new.html.erb
<% content_for :title, "New product" %>

<h1>New product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/show.html.erb
<p style="color: green"><%= notice %></p>

<article class="product-details">
  <header>
    <h1><%= @product.name %></h1>
  </header>

  <section class="product-info">
    <dl>
      <div class="info-row">
        <dt>Price:</dt>
        <dd><%= number_to_currency(@product.price) %></dd>
      </div>

      <div class="info-row">
        <dt>Brand:</dt>
        <dd><%= @product.brand&.name || "No brand assigned" %></dd>
      </div>

      <div class="info-row">
        <dt>Category:</dt>
        <dd><%= @product.category&.name || "No category assigned" %></dd>
      </div>
    </dl>
  </section>

  <nav class="product-actions">
    <%= link_to "Edit", edit_product_path(@product), class: "button" %> |
    <%= link_to "Back to Products", products_path, class: "button" %>
  </nav>
</article>